In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
'load killings'
police = pd.read_csv('fatal-police-shootings-data.csv')
police['city'] = police['city'].str.replace(r' city', '') #removes anything with a lower-cased ' city', done to try to clean up data
police['city'] = police['city'].str.replace(r'St ', 'St. ')#St Louis in police is St. Louis in CityPopulation2000
police['city'] = police['city'].str.replace(r'\-.*', '')#removes everything after -, used to add more per capita counts 

police

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False
5,11,Kenneth Joe Brown,2015-01-04,shot,gun,18.0,M,W,Guthrie,OK,False,attack,Not fleeing,False
6,13,Kenneth Arnold Buck,2015-01-05,shot,gun,22.0,M,H,Chandler,AZ,False,attack,Car,False
7,15,Brock Nichols,2015-01-06,shot,gun,35.0,M,W,Assaria,KS,False,attack,Not fleeing,False
8,16,Autumn Steele,2015-01-06,shot,unarmed,34.0,F,W,Burlington,IA,False,other,Not fleeing,True
9,17,Leslie Sapp III,2015-01-06,shot,toy weapon,47.0,M,B,Knoxville,PA,False,attack,Not fleeing,False
10,19,Patrick Wetter,2015-01-06,shot and Tasered,knife,25.0,M,W,Stockton,CA,False,attack,Not fleeing,False
11,21,Ron Sneed,2015-01-07,shot,gun,31.0,M,B,Freeport,TX,False,attack,Not fleeing,False
12,22,Hashim Hanif Ibn Abdul-Rasheed,2015-01-07,shot,knife,41.0,M,B,Columbus,OH,True,other,Not fleeing,False
13,25,Nicholas Ryan Brickman,2015-01-07,shot,gun,30.0,M,W,Des Moines,IA,False,attack,Car,False
14,27,Omarr Julian Maximillian Jackson,2015-01-07,shot,gun,37.0,M,B,New Orleans,LA,False,attack,Foot,True
15,29,Loren Simpson,2015-01-08,shot,NaN,28.0,M,W,Huntley,MT,False,undetermined,Not fleeing,False
16,32,James Dudley Barker,2015-01-08,shot,shovel,42.0,M,W,Salt Lake City,UT,False,attack,Not fleeing,True
17,36,Artago Damon Howard,2015-01-08,shot,unarmed,36.0,M,B,Strong,AR,False,attack,Not fleeing,False
18,37,Thomas Hamby,2015-01-08,shot,gun,49.0,M,W,Syracuse,UT,False,attack,Not fleeing,True
19,38,Jimmy Foreman,2015-01-09,shot,gun,71.0,M,W,England,AR,False,attack,Not fleeing,False
20,325,Andy Martinez,2015-01-09,shot,gun,33.0,M,H,El Paso,TX,False,attack,Not fleeing,False
21,42,Tommy Smith,2015-01-11,shot,gun,39.0,M,W,Arcola,IL,True,attack,Not fleeing,False
22,43,Brian Barbosa,2015-01-11,shot,gun,23.0,M,H,South Gate,CA,False,attack,Not fleeing,False
23,45,Salvador Figueroa,2015-01-11,shot and Tasered,gun,29.0,M,H,North Las Vegas,NV,False,attack,Foot,False
24,46,John Edward O'Keefe,2015-01-13,shot,gun,34.0,M,W,Albuquerque,NM,False,attack,Foot,True
25,48,Richard McClendon,2015-01-13,shot,knife,43.0,M,W,Jourdanton,TX,True,other,Not fleeing,False
26,49,Marcus Golden,2015-01-14,shot,NaN,24.0,M,B,St. Paul,MN,False,attack,Not fleeing,False
27,50,Michael Goebel,2015-01-14,shot,NaN,29.0,M,W,Franklin County,MO,False,attack,Not fleeing,False
28,51,Mario Jordan,2015-01-14,shot,gun,34.0,M,B,Chesapeake,VA,True,attack,Not fleeing,False
29,52,Talbot Schroeder,2015-01-14,shot,knife,75.0,M,W,Old Bridge,NJ,False,attack,Not fleeing,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4687,5147,Michael Pinkerman,2019-10-30,shot,gun,NaN,M,W,Ona,WV,False,attack,Not fleeing,False
4688,5149,TK TK,2019-10-30,shot,knife,NaN,M,NaN,San Jose,CA,False,other,Not fleeing,False
4689,5162,Billy Kongphouthakhoun,2019-10-30,shot,gun,NaN,M,A,Fresno,CA,False,other,Not fleeing,False
4690,5163,TK TK,2019-10-30,shot,ax,NaN,M,NaN,Lancaster,CA,False,other,Not fleeing,False
4691,5160,Danny James Hall,2019-10-31,shot,gun,34.0,M,W,Bascom,FL,False,attack,Car,False
4692,5161,TK TK,2019-10-31,shot,toy weapon,NaN,M,NaN,San Jose,CA,False,attack,Not fleeing,False
4693,5150,Benjamin Diaz,2019-11-01,shot,sharp object,22.0,M,H,Alamogordo,NM,False,attack,Car,False
4694,5158,TK TK,2019-11-01,shot,undetermined,NaN,M,NaN,Adams County,CO,False,undetermined,NaN,False
4695,5159,Luis Morales-Camacho,2019-11-01,shot,undetermined,41.0,M,H,Orlando,FL,False,attack,Not fleeing,False
4696,5173,Luis Fino Nabarrette,2019-11-01,shot,gun,38.0,M,H,Odessa,TX,False,attack,Car,False
4697,5155,Michael Kifer,2019-11-02,shot and Tasered,sword,29.0,M,W,Vero Beach,FL,False,attack,Not fleeing,False
4698,5157,John Hale,2019-11-02,shot,undetermined,42.0,M,W,Dexter,KY,False,attack,NaN,False
4699,5153,TK TK,2019-11-03,shot,knife,56.0,M,NaN,Parkland,WA,False,other,Not fleeing,False
4700,5154,Michael Austin,2019-11-03,shot,gun,32.0,M,B,Phoenix,AZ,False,attack,Not fleeing,False
4701,5151,TK TK,2019-11-04,shot,gun,NaN,M,NaN,Sunland Park,NM,False,attack,Foot,False
4702,5172,Matthew Rasmussen,2019-11-04,shot,sharp object,31.0,M,W,Glendale,AZ,True,attack,Not fleeing,False
4703,5174,Daniel M. Munoz,2019-11-04,shot,gun,21.0,M,H,Las Cruces,NM,False,attack,NaN,False
4704,5175,TK TK,2019-11-04,shot,gun,NaN,M,NaN,Two Rivers,WI,False,other,Not fleeing,False
4705,5167,Maurice Brown,2019-11-05,shot,gun,48.0,M,B,East Cleveland,OH,False,attack,Not fleeing,True
4706,5168,Jay P. Messer,2019-11-05,shot,gun,58.0,M,NaN,Pettis County,MO,False,attack,Not fleeing,False
4707,5169,TK TK,2019-11-05,shot,gun,NaN,M,NaN,Leon,WI,False,other,Not fleeing,False
4708,5171,Christopher Alan Noe,2019-11-05,shot and Tasered,knife,45.0,M,NaN,Willis,TX,False,other,Car,False
4709,5164,Eddie Ray Maxwell,2019-11-06,shot,gun,37.0,M,B,Tahlequah,OK,False,attack,Not fleeing,False
4710,5165,Corben Hunter Jones,2019-11-06,shot,undetermined,20.0,M,W,Henryetta,OK,False,undetermined,NaN,False
4711,5166,TK TK,2019-11-06,shot,gun,NaN,M,NaN,San Antonio,TX,False,other,NaN,False
4712,5170,Treva Smutherman,2019-11-06,shot,gun,31.0,M,B,Fayetteville,NC,False,attack,Not fleeing,False
4713,5176,Guy Thomas Barnard,2019-11-07,shot,BB gun,26.0,M,NaN,Wadsworth,OH,False,attack,NaN,False
4714,5177,TK TK,2019-11-07,shot,gun,NaN,M,NaN,Louisville,KY,False,attack,NaN,False
4715,5178,Gerald Newton Allen,2019-11-07,shot,gun,66.0,M,NaN,Conyers,GA,False,attack,Not fleeing,False
4716,5179,Christopher Mills,2019-11-07,shot,gun,37.0,M,NaN,Ashtabula Township,OH,False,other,Not fleeing,False

In [3]:
print(police['race'].value_counts())
o = police.copy()
not_o = o[o['race'] != 'O' ].index
o.drop(not_o, inplace=True)
o

W    2106
B    1102
H     802
A      79
N      72
O      40
Name: race, dtype: int64

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
38,68,Zaki Shinwary,2015-01-16,shot and Tasered,knife,48.0,M,O,Fremont,CA,False,other,Not fleeing,False
327,418,Fridoon Zalbeg Nehad,2015-04-30,shot,unarmed,42.0,M,O,San Diego,CA,True,other,Not fleeing,True
332,428,Nadir Soofi,2015-05-03,shot,gun,34.0,M,O,Garland,TX,False,attack,Not fleeing,False
352,449,Bruce Zalonka,2015-05-12,shot and Tasered,gun,46.0,M,O,Honolulu,HI,False,attack,Not fleeing,False
387,491,Feras Morad,2015-05-27,shot and Tasered,unarmed,20.0,M,O,Long Beach,CA,False,other,Not fleeing,False
524,649,Mohammad Youssef Abdulazeez,2015-07-16,shot,gun,24.0,M,O,Chattanooga,TN,True,attack,Not fleeing,False
724,857,Robert Berger,2015-09-23,shot,knife,48.0,M,O,Salt Lake City,UT,False,attack,Not fleeing,False
731,865,Philip Quinn,2015-09-24,shot,screwdriver,30.0,M,O,St. Paul,MN,True,other,Not fleeing,False
754,895,Omar Ali,2015-10-05,shot,unarmed,27.0,M,O,Akron,OH,False,other,Not fleeing,False
813,956,Kobvey Igbuhay,2015-10-26,shot,unarmed,18.0,M,O,Tampa,FL,False,attack,Foot,False
836,979,Faisal Mohammad,2015-11-04,shot,knife,18.0,M,O,Merced,CA,False,attack,Foot,False
909,1050,Tashfeen Malik,2015-12-02,shot,gun,27.0,F,O,San Bernardino,CA,False,attack,Car,False
910,1051,Syed Farook,2015-12-02,shot,gun,28.0,M,O,San Bernardino,CA,False,attack,Car,False
943,1084,Nephi Leiataua,2015-12-13,shot,knife,30.0,M,O,Thurston County,WA,False,attack,Not fleeing,False
989,1133,Siolosega Velega-Nuufolau,2015-12-29,shot,knife,50.0,F,O,Santa Nella,CA,True,other,Not fleeing,False
1086,1242,Ronald Barawis,2016-02-05,shot,NaN,38.0,M,O,Hilo,HI,False,other,Car,False
1098,1256,Scottie Yanagawa,2016-02-09,shot,gun,29.0,M,O,Hilo,HI,False,attack,Not fleeing,False
1103,1260,Anthony Bertoni,2016-02-10,shot,gun,56.0,M,O,Henderson County,TX,True,attack,Not fleeing,False
1340,1529,Derek J. Sam,2016-05-07,shot and Tasered,knife,29.0,M,O,Presque Isle,ME,False,other,Not fleeing,False
1412,1597,Kalyp Allen Rapoza,2016-06-06,shot,knife,25.0,M,O,Hilo,HI,False,other,Not fleeing,False
1429,1608,Omar Mateen,2016-06-12,shot,gun,29.0,M,O,Orlando,FL,True,attack,Not fleeing,True
1438,1624,Mohammad Moghaddam,2016-06-14,shot,gun,54.0,M,O,Amarillo,TX,False,attack,Not fleeing,False
1536,1724,BJ Medeiros,2016-07-21,shot,gun,36.0,M,O,Hilo,HI,True,attack,Not fleeing,False
1693,1898,Dahir Adan,2016-09-17,shot,knife,22.0,M,O,St. Cloud,MN,False,attack,Not fleeing,False
1870,2083,Abdul Razak Ali Artan,2016-11-28,shot,knife,18.0,M,O,Columbus,OH,False,attack,Not fleeing,False
1897,2115,Stephen Joshua Whitney,2016-12-09,shot,NaN,30.0,M,O,Keaau,HI,False,other,Not fleeing,False
1984,2210,Hafez Abousamra,2017-01-11,shot,gun,41.0,M,O,Lake Elsinore,CA,False,attack,Other,False
1989,2218,Cameron Johnson,2017-01-13,shot,NaN,29.0,M,O,Kahuku,HI,False,other,Car,False
2393,2654,Isaiah Obet,2017-06-10,shot,knife,25.0,M,O,Auburn,WA,False,other,Car,False
2509,2791,Farhad Jabbari,2017-07-19,shot,unarmed,38.0,M,O,Saginaw,MI,False,attack,Not fleeing,False
2673,2973,Austin Dunsmore,2017-09-21,shot,undetermined,25.0,M,O,Denver,CO,False,other,Car,False
2676,2977,Dillan Tabares,2017-09-22,shot,gun,27.0,M,O,Huntington Beach,CA,True,attack,Not fleeing,False
3472,3841,Steven Allan Kaluahinui Hyer Jr.,2018-06-23,shot,bow and arrow,32.0,M,O,North Shore,HI,True,attack,Not fleeing,False
3542,3944,Justin Waiki,2018-07-20,shot,gun,33.0,M,O,Puna,HI,False,attack,Car,False
3740,4099,Ashley Elisna Grammer,2018-10-12,shot,vehicle,26.0,F,O,Puna,HI,False,attack,Not fleeing,False
3915,4329,"Kaulana ""Toji"" Reinhardt",2018-12-23,shot,gun,NaN,M,O,Wailuku,HI,False,attack,Car,True
4023,4423,Siatu'u Tauai,2019-01-29,shot,vehicle,51.0,M,O,Kalihi,HI,False,attack,Car,False
4081,4472,Kasim Kahrim,2019-02-22,shot,gun,36.0,M,O,Boston,MA,False,attack,Car,False
4296,4742,Ronnie Churches,2019-05-19,shot,gun,45.0,M,O,Miami Gardens,FL,False,attack,Not fleeing,False
4399,4838,Isak Abdirahman Aden,2019-07-02,shot,gun,23.0,M,O,Eagan,MN,False,other,Foot,True

In [4]:
'loading population'
city_population = pd.read_csv('CityPopulation2000.csv', encoding = "ISO-8859-1")

print(city_population.dtypes) #shows the type of data contained in cells

city_population['Population'] = city_population['Population'].str.replace(r'\(r.*\)', '')#removes anything that has a (r) in it, done to try to clean up data
city_population['City'] = city_population['City'].str.replace(r"[\s\S]*.*(balance).*[\s\S]", '')#removes everything in a cell if it has (balance) in it,prevents double counting 
city_population['City'] = city_population['City'].str.replace(r'\(.*\)', '')#removes anything that has a parenthesis in it, done to try to clean up data
city_population['City'] = city_population['City'].str.replace(r' CDP', '')#removes anything that has a 'CDP' in it, done to try to clean up data
city_population['City'] = city_population['City'].str.replace(r' city', '')#removes anything that has a lowercase spelling of 'city' in it, done to try to clean up data
city_population['City'] = city_population['City'].str.replace(r' village', '')#removes lowercase villages
city_population['City'] = city_population['City'].str.replace(r' municipality', '')#removes municipality, mainly to deal with Anchorage
city_population['City'] = city_population['City'].str.replace(r' town', '')#removes lowercase town
city_population['City'] = city_population['City'].str.replace(r'Urban ', '')#Removes Urban , for Honolulu
city_population['City'] = city_population['City'].str.replace(r'\-.*', '')#removes everything after -, used to add more per capita counts 
city_population['City'] = city_population['City'].str.replace(r'\/.*', '')#removes everything after /, used to add more per capita counts 

type_dict = {'Geographic Area': 'str', 'City': 'str', 'Population': 'int64'}#done to change population values into an integer
city_population = city_population.astype(type_dict)#done to change population values into an integer

print(city_population.dtypes)
print(len(city_population))

drop_pop = city_population[city_population['Population'] == 0].index
city_population.drop(drop_pop, inplace=False)

print(len(city_population))

city_population

Geographic Area    object
City               object
Population         object
dtype: object
Geographic Area    object
City               object
Population          int64
dtype: object
29523
29503

      Geographic Area                               City  Population
0                  AL                             Abanda         192
1                  AL                          Abbeville        2688
2                  AL                         Adamsville        4522
3                  AL                            Addison         758
4                  AL                              Akron         356
5                  AL                          Alabaster       30352
6                  AL                        Albertville       21160
7                  AL                     Alexander City       14875
8                  AL                         Alexandria        3917
9                  AL                         Aliceville        2486
10                 AL                            Allgood         622
11                 AL                            Altoona         933
12                 AL                          Andalusia        9015
13                 AL                           Anderson         282
14                 AL                           Anniston       23106
15                 AL                               Arab        8050
16                 AL                            Ardmore        1194
17                 AL                               Argo        4071
18                 AL                             Ariton         764
19                 AL                              Arley         357
20                 AL                            Ashford        2148
21                 AL                            Ashland        2037
22                 AL                           Ashville        2212
23                 AL                             Athens       21897
24                 AL                             Atmore       10194
25                 AL                            Attalla        6048
26                 AL                             Auburn       53380
27                 AL                       Autaugaville         870
28                 AL                               Avon         543
29                 AL                               Axis         757
...               ...                                ...         ...
29493     Puerto Rico               San Isidro comunidad        6828
29494     Puerto Rico                 San José comunidad        2900
29495     Puerto Rico               San Juan zona urbana      381931
29496     Puerto Rico            San Lorenzo zona urbana        8037
29497     Puerto Rico          San Sebastián zona urbana        9622
29498     Puerto Rico            Santa Bárbara comunidad        4622
29499     Puerto Rico              Santa Clara comunidad         982
29500     Puerto Rico           Santa Isabel zona urbana        5976
29501     Puerto Rico            Santo Domingo comunidad        3156
29502     Puerto Rico                   Stella comunidad        1088
29503     Puerto Rico                   Suárez comunidad        1931
29504     Puerto Rico                 Tallaboa comunidad         925
29505     Puerto Rico            Tallaboa Alta comunidad        1816
29506     Puerto Rico                    Tibes comunidad         362
29507     Puerto Rico                Tiburones comunidad        1616
29508     Puerto Rico  Tierras Nuevas Poniente comunidad        3228
29509     Puerto Rico               Toa Alta zona urbana        3713
29510     Puerto Rico               Toa Baja zona urbana        1513
29511     Puerto Rico          Trujillo Alto zona urbana       48437
29512     Puerto Rico                 Utuado zona urbana        8397
29513     Puerto Rico                    Vayas comunidad         528
29514     Puerto Rico                  Vázquez comunidad        1890
29515     Puerto Rico              Vega Alta zona urbana       10266
29516     Puerto Rico              Vega Baja zona urbana       25905
29517     Puerto Rico                  Vieques comunidad        3316
29518     Puerto Rico                Vieques zona urbana        1938
29519     Puerto Rico               Villalba zona urbana        3384
29520     Puerto Rico                Yabucoa zona urbana        6047
29521     Puerto Rico                  Yauco zona urbana       17186
29522     Puerto Rico                   Yaurel comunidad        1050

[29503 rows x 3 columns]

In [6]:
city_population[630]

KeyError: 630

In [5]:
'make a list of city populations'
city_pop_lst=[]
for i in range(len(city_population)):
    city_pop_lst.append([city_population['City'][i],city_population['Population'][i],city_population['Geographic Area'][i]])
print(len(city_pop_lst))
city_pop_lst

KeyError: 630

In [ ]:
'Adding Income'
comp_1_i = pd.read_csv('MedianHouseholdIncome2015.csv', encoding = "ISO-8859-1")

comp_1_i['Median Income'] = comp_1_i['Median Income'].str.replace(r'\(.*\)', '0')#removes anything that has a () in it, done to try to clean up data
comp_1_i['Median Income'] = comp_1_i['Median Income'].str.replace(r'.*\-.*', '0')
comp_1_i['Median Income'] = comp_1_i['Median Income'].str.replace(r'\+', '')
comp_1_i['Median Income'] = comp_1_i['Median Income'].str.replace(r'\,', '')
comp_1_i['City'] = comp_1_i['City'].str.replace(r'\-.*', '')#removes everything after -, used to add more per capita counts 
comp_1_i['City'] = comp_1_i['City'].str.replace(r'\/.*', '')#removes everything after /, used to add more per capita counts 
comp_1_i['City'] = comp_1_i['City'].str.replace(r" (balance)", '')#removes everything in a cell if it has (balance) in it,prevents double counting 
comp_1_i['City'] = comp_1_i['City'].str.replace(r'\(.*\)', '')#removes anything that has a parenthesis in it, done to try to clean up data
comp_1_i['City'] = comp_1_i['City'].str.replace(r' CDP', '')#removes anything that has a 'CDP' in it, done to try to clean up data
comp_1_i['City'] = comp_1_i['City'].str.replace(r' city', '')#removes anything that has a lowercase spelling of 'city' in it, done to try to clean up data
comp_1_i['City'] = comp_1_i['City'].str.replace(r' village', '')#removes lowercase villages
comp_1_i['City'] = comp_1_i['City'].str.replace(r' municipality', '')#removes municipality, mainly to deal with Anchorage
comp_1_i['City'] = comp_1_i['City'].str.replace(r' town', '')#removes lowercase town
comp_1_i['City'] = comp_1_i['City'].str.replace(r'Urban ', '')#Removes Urban , for Honolulu


type_dict = {'Geographic Area': 'str', 'City': 'str', 'Median Income': 'int64'}#done to change population values into an integer
comp_1_i = comp_1_i.astype(type_dict)#done to change population values into an integer

In [ ]:
'making data useable'
comp_1_i_lst=[]
for i in range(len(comp_1_i)):
    comp_1_i_lst.append([comp_1_i['City'][i],comp_1_i['Median Income'][i],comp_1_i['Geographic Area'][i]])

In [ ]:
'Adding Poverty Rate'
comp_2 = pd.read_csv('PercentagePeopleBelowPovertyLevel.csv', encoding = "ISO-8859-1")

comp_2['poverty_rate'] = comp_2['poverty_rate'].str.replace(r'\(.*\)', '0')#removes anything that has a () in it, done to try to clean up data
comp_2['poverty_rate'] = comp_2['poverty_rate'].str.replace(r'.*\-.*', '0')
comp_2['poverty_rate'] = comp_2['poverty_rate'].str.replace(r'\+', '')
comp_2['poverty_rate'] = comp_2['poverty_rate'].str.replace(r'\,', '')
comp_2['City'] = comp_2['City'].str.replace(r'\-.*', '')#removes everything after -, used to add more per capita counts 
comp_2['City'] = comp_2['City'].str.replace(r'\/.*', '')#removes everything after /, used to add more per capita counts 
comp_2['City'] = comp_2['City'].str.replace(r" (balance)", '')#removes everything in a cell if it has (balance) in it,prevents double counting 
comp_2['City'] = comp_2['City'].str.replace(r'\(.*\)', '')#removes anything that has a parenthesis in it, done to try to clean up data
comp_2['City'] = comp_2['City'].str.replace(r' CDP', '')#removes anything that has a 'CDP' in it, done to try to clean up data
comp_2['City'] = comp_2['City'].str.replace(r' city', '')#removes anything that has a lowercase spelling of 'city' in it, done to try to clean up data
comp_2['City'] = comp_2['City'].str.replace(r' village', '')#removes lowercase villages
comp_2['City'] = comp_2['City'].str.replace(r' municipality', '')#removes municipality, mainly to deal with Anchorage
comp_2['City'] = comp_2['City'].str.replace(r' town', '')#removes lowercase town
comp_2['City'] = comp_2['City'].str.replace(r'Urban ', '')#Removes Urban , for Honolulu


type_dict = {'Geographic Area': 'str', 'City': 'str', 'poverty_rate': 'float64'}#done to change population values into an integer
comp_2 = comp_2.astype(type_dict)#done to change population values into an integer

In [ ]:
'making data useable'
comp_2_lst=[]
for i in range(len(comp_2)):
    comp_2_lst.append([comp_2['City'][i],comp_2['poverty_rate'][i],comp_2['Geographic Area'][i]])

In [ ]:
'Adding Education'
comp_3 = pd.read_csv('PercentOver25CompletedHighSchool.csv', encoding = "ISO-8859-1")

comp_3['percent_completed_hs'] = comp_3['percent_completed_hs'].str.replace(r'\(.*\)', '0')#removes anything that has a () in it, done to try to clean up data
comp_3['percent_completed_hs'] = comp_3['percent_completed_hs'].str.replace(r'.*\-.*', '0')
comp_3['percent_completed_hs'] = comp_3['percent_completed_hs'].str.replace(r'\+', '')
comp_3['percent_completed_hs'] = comp_3['percent_completed_hs'].str.replace(r'\,', '')
comp_3['City'] = comp_3['City'].str.replace(r'\-.*', '')#removes everything after -, used to add more per capita counts 
comp_3['City'] = comp_3['City'].str.replace(r'\/.*', '')#removes everything after /, used to add more per capita counts 
comp_3['City'] = comp_3['City'].str.replace(r" (balance)", '')#removes everything in a cell if it has (balance) in it,prevents double counting 
comp_3['City'] = comp_3['City'].str.replace(r'\(.*\)', '')#removes anything that has a parenthesis in it, done to try to clean up data
comp_3['City'] = comp_3['City'].str.replace(r' CDP', '')#removes anything that has a 'CDP' in it, done to try to clean up data
comp_3['City'] = comp_3['City'].str.replace(r' city', '')#removes anything that has a lowercase spelling of 'city' in it, done to try to clean up data
comp_3['City'] = comp_3['City'].str.replace(r' village', '')#removes lowercase villages
comp_3['City'] = comp_3['City'].str.replace(r' municipality', '')#removes municipality, mainly to deal with Anchorage
comp_3['City'] = comp_3['City'].str.replace(r' town', '')#removes lowercase town
comp_3['City'] = comp_3['City'].str.replace(r'Urban ', '')#Removes Urban , for Honolulu


type_dict = {'Geographic Area': 'str', 'City': 'str', 'percent_completed_hs': 'float64'}#done to change population values into an integer
comp_3 = comp_3.astype(type_dict)#done to change population values into an integer

In [ ]:
'making data useable'
comp_3_lst=[]
for i in range(len(comp_3)):
    comp_3_lst.append([comp_3['City'][i],comp_3['percent_completed_hs'][i],comp_3['Geographic Area'][i]])

In [ ]:
'Adding Race'
comp_4 = pd.read_csv('ShareRaceByCity.csv', encoding = "ISO-8859-1")
print(len(comp_4))

print(comp_4.dtypes) #shows the type of data contained in cells

print(len(comp_4))

comp_4['share_white'] = comp_4['share_white'].str.replace(r'\(.*\)', '0')#removes anything that has a () in it, done to try to clean up data
comp_4['share_white'] = comp_4['share_white'].str.replace(r'.*\-.*', '0')
comp_4['share_white'] = comp_4['share_white'].str.replace(r'\+', '')
comp_4['share_white'] = comp_4['share_white'].str.replace(r'\,', '')

comp_4['share_black'] = comp_4['share_black'].str.replace(r'\(.*\)', '0')#removes anything that has a () in it, done to try to clean up data
comp_4['share_black'] = comp_4['share_black'].str.replace(r'.*\-.*', '0')
comp_4['share_black'] = comp_4['share_black'].str.replace(r'\+', '')
comp_4['share_black'] = comp_4['share_black'].str.replace(r'\,', '')

comp_4['share_native_american'] = comp_4['share_native_american'].str.replace(r'\(.*\)', '0')#removes anything that has a () in it, done to try to clean up data
comp_4['share_native_american'] = comp_4['share_native_american'].str.replace(r'.*\-.*', '0')
comp_4['share_native_american'] = comp_4['share_native_american'].str.replace(r'\+', '')
comp_4['share_native_american'] = comp_4['share_native_american'].str.replace(r'\,', '')

comp_4['share_asian'] = comp_4['share_asian'].str.replace(r'\(.*\)', '0')#removes anything that has a () in it, done to try to clean up data
comp_4['share_asian'] = comp_4['share_asian'].str.replace(r'.*\-.*', '0')
comp_4['share_asian'] = comp_4['share_asian'].str.replace(r'\+', '')
comp_4['share_asian'] = comp_4['share_asian'].str.replace(r'\,', '')

comp_4['share_hispanic'] = comp_4['share_hispanic'].str.replace(r'\(.*\)', '0')#removes anything that has a () in it, done to try to clean up data
comp_4['share_hispanic'] = comp_4['share_hispanic'].str.replace(r'.*\-.*', '0')
comp_4['share_hispanic'] = comp_4['share_hispanic'].str.replace(r'\+', '')
comp_4['share_hispanic'] = comp_4['share_hispanic'].str.replace(r'\,', '')

comp_4['City'] = comp_4['City'].str.replace(r'\-.*', '')#removes everything after -, used to add more per capita counts 
comp_4['City'] = comp_4['City'].str.replace(r'\/.*', '')#removes everything after /, used to add more per capita counts 
comp_4['City'] = comp_4['City'].str.replace(r" (balance)", '')#removes everything in a cell if it has (balance) in it,prevents double counting 
comp_4['City'] = comp_4['City'].str.replace(r'\(.*\)', '')#removes anything that has a parenthesis in it, done to try to clean up data
comp_4['City'] = comp_4['City'].str.replace(r' CDP', '')#removes anything that has a 'CDP' in it, done to try to clean up data
comp_4['City'] = comp_4['City'].str.replace(r' city', '')#removes anything that has a lowercase spelling of 'city' in it, done to try to clean up data
comp_4['City'] = comp_4['City'].str.replace(r' village', '')#removes lowercase villages
comp_4['City'] = comp_4['City'].str.replace(r' municipality', '')#removes municipality, mainly to deal with Anchorage
comp_4['City'] = comp_4['City'].str.replace(r' town', '')#removes lowercase town
comp_4['City'] = comp_4['City'].str.replace(r'Urban ', '')#Removes Urban , for Honolulu


type_dict_4 = {'Geographic Area': 'str', 'City': 'str', 'share_white': 'float64', 'share_black': 'float64', 'share_native_american': 'float64', 'share_asian': 'float64', 'share_hispanic': 'float64'}#done to change population values into an integer

comp_4 = comp_4.astype(type_dict_4)#done to change population values into an integer


print(len(comp_4))


len(comp_4)

In [ ]:
'making data useable'
comp_4_lst=[]
for i in range(len(comp_4)):
    comp_4_lst.append([comp_4['City'][i],[float(comp_4['share_white'][i]),float(comp_4['share_black'][i]),float(comp_4['share_native_american'][i]),float(comp_4['share_asian'][i]),float(comp_4['share_hispanic'][i])],comp_4['Geographic Area'][i]])

In [ ]:
'making a few functions to help later'
def find_city(city_name,lst):
    for i in range(len(lst)):
        if city_name in lst[i][0]:
            print(lst[i])
            print(i)
def find_repeats(lst):
    for i in range(len(lst)):
        if len(lst[i])>4:
            print(lst[i])
def find_emptys(lst):
    for i in range(len(lst)):
        if len(lst[i])==3:
            print(lst[i])
killings_per_capita_eq_n=city_kill_state_n.copy()
killings_per_capita_eq_a=city_kill_state_a.copy()
killings_per_capita_eq_h=city_kill_state_h.copy()
killings_per_capita_eq_w=city_kill_state_w.copy()
killings_per_capita_eq_b=city_kill_state_b.copy()

In [ ]:
"making the function that makes list of kills per capita"
def per_capita(city_kill_state,city_pop_lst):
    for i in range(len(city_kill_state)):
        for x in range(len(city_pop_lst)):
            if city_kill_state[i][0] == city_pop_lst[x][0]:
                if city_kill_state[i][2] == city_pop_lst[x][2]:
                    per_capita =100000 * float(city_kill_state[i][1])/float(city_pop_lst[x][1])
                    city_kill_state[i].extend([float(city_pop_lst[x][1]),per_capita])
    print(len(city_kill_state))
    return city_kill_state

In [ ]:
'adding data'
def add_income(fatal_police_shootings_per_capita,comp_1_i_lst):
    for i in range(len(fatal_police_shootings_per_capita)):
        for x in range(len(comp_1_i_lst)):
            if fatal_police_shootings_per_capita[i][0] == comp_1_i_lst[x][0]:
                if fatal_police_shootings_per_capita[i][2] == comp_1_i_lst[x][2]:
                    fatal_police_shootings_per_capita[i].append(comp_1_i_lst[x][1])
    print(len(fatal_police_shootings_per_capita))
    return fatal_police_shootings_per_capita

In [ ]:
'adding data'
def add_poverty(fatal_police_shootings_per_capita,comp_2_lst):
    for i in range(len(fatal_police_shootings_per_capita)):
        for x in range(len(comp_2_lst)):
            if fatal_police_shootings_per_capita[i][0] == comp_2_lst[x][0]:
                if fatal_police_shootings_per_capita[i][2] == comp_2_lst[x][2]:
                    fatal_police_shootings_per_capita[i].append(comp_2_lst[x][1])
    print(len(fatal_police_shootings_per_capita))
    return fatal_police_shootings_per_capita

In [ ]:
'adding data'
def add_edu(fatal_police_shootings_per_capita,comp_3_lst):
    for i in range(len(fatal_police_shootings_per_capita)):
        for x in range(len(comp_3_lst)):
            if fatal_police_shootings_per_capita[i][0] == comp_3_lst[x][0]:
                if fatal_police_shootings_per_capita[i][2] == comp_3_lst[x][2]:
                    fatal_police_shootings_per_capita[i].append(comp_3_lst[x][1])
    print(len(fatal_police_shootings_per_capita))
    return fatal_police_shootings_per_capita

In [ ]:
'adding data'
def add_races(fatal_police_shootings_per_capita,comp_4_lst):
    for i in range(len(fatal_police_shootings_per_capita)):
        for x in range(len(comp_4_lst)):
            if fatal_police_shootings_per_capita[i][0] == comp_4_lst[x][0]:
                if fatal_police_shootings_per_capita[i][2] == comp_4_lst[x][2]:
                    fatal_police_shootings_per_capita[i].extend(comp_4_lst[x][1])
    print(len(fatal_police_shootings_per_capita))
    return fatal_police_shootings_per_capita
add_races(fatal_police_shootings_per_capita_n,comp_4_lst)
add_races(fatal_police_shootings_per_capita_a,comp_4_lst)
add_races(fatal_police_shootings_per_capita_h,comp_4_lst)
add_races(fatal_police_shootings_per_capita_w,comp_4_lst)
add_races(fatal_police_shootings_per_capita_b,comp_4_lst)

In [ ]:
'checking for empties'
def empty(fatal_police_shootings_per_capita):
    print(len(fatal_police_shootings_per_capita))
    sfdgdfsg=[]
    for i in range(len(fatal_police_shootings_per_capita)):
        if len(fatal_police_shootings_per_capita[i])<13:
            sfdgdfsg.append(fatal_police_shootings_per_capita[i])
            print(fatal_police_shootings_per_capita[i])
    print(len(sfdgdfsg))
    sfdgdfsg=[]
empty(fatal_police_shootings_per_capita_n)
empty(fatal_police_shootings_per_capita_a)
empty(fatal_police_shootings_per_capita_h)
empty(fatal_police_shootings_per_capita_w)
empty(fatal_police_shootings_per_capita_b)

In [ ]:
'Adding Cañon City'
find_city('Cañon City',fatal_police_shootings_per_capita_w)
[float(41892),20.6,91.1,96.0,1.2,0.6,0.2,10.5]
fatal_police_shootings_per_capita_w[189].extend([float(41892),20.6,91.1,96.0,1.2,0.6,0.2,10.5])
empty(fatal_police_shootings_per_capita_w)

In [ ]:
#DON'T DELETE THIS




'''NOTE TO LARRY LATER: I HEAVILY LEAN TOWARDS JUST USING ==, MESS AROUND WITH THE CLEANING OF Population A BIT TO SEE JUST HOW MUCH WE REALLY NEED TO CLEAN THE SHIT
ONE PARTICULAR NOTE IS ANCHORAGE, WHY IS IT EMPTY?'''
'having a space messed things up about as much as keeping CDP'
'spaces and city no lowercase did about the same, one more knocked off'
'lower case removed 3 from the good list'
'Anchorage is Anchorage municipality...'
'town and village also had to be removed, they started with lowercases'
'''put Affton MO into presentation as an example of what to do with CDPs and 
why you had to strike them off''' '~300'
"Athens, georgia, is actually Athens-Clarke County unified government"
"Augusta, georgia has the same problem"
"Barona Indian Reservation, Indian Reservations probably aren't counted"
"Boise Idaho, is Boise City, Idaho in the Census..."
"Bon Aqua TX, is Bon Aqua Junction"
"Braintree MA is Braintree Town city"
"Bronx, Brooklyn, Queens aren't in NY..."
"Byram NJ, Byram Township isn't on the excel..."
"Louisville KY is Louisville/Jefferson County metro government"'~4'
"Nashville is Nashville-Davidson metropolitan government"'~10'
"Honolulu had Urban in front of it"
"the ones with a long ass name are double counted too..."
"Florence CA is Florence-Graham CA"
"St in police is St. in population"'~20'
'''  everyting with a - in it
['Grant-Valkaria', 1, 'FL', 0.00025974025974025974]
['Helena-West Helena', 1, 'AR', 8.141996417521577e-05]
['Opa-Locka', 1, 'FL']
['Pinetop-Lakeside', 1, 'AZ', 0.00023353573096683791]
['Soddy-Daisy', 2, 'TN', 0.00015730690577316344]
['Winston-Salem', 1, 'NC', 4.3550782389805635e-06]'''
'''for some reason a lot of the cities had (balance) in the names, we weren't
sure why it's there because the line above them always had the same city
Happened to Athens, August GA, Indianopolis, Louisville, Nashville
Most didn't have more than 5000 ppl difference, but Nashville had 20k 
differenceand Louisville has a 200k difference...
'''
'''Geneva WI isnt in census,  Hollywood isnt in the Census(prob belings with 
the NY stuff),  Puna isnt in Census,  theres like 50 more in the cities with 
only one police shootings, but Im not gonna go through all of them'''





"we should manually Add Washington DC, Boise and Louisville"

In [ ]:
'''for Median Income and Race: modified Washington DC and indianopolis to remove hanging space, New York City changed to New York, Boise City changed to Boise'''

In [ ]:
'''for all the other ones and Race, Athens, Augusta, Butte, Louisville, and Nashville needed to have their (balance) parts removed'''

In [ ]:
'I should also split this by racial data too'
'Also lets include racial data as well'

In [ ]:
'this thing is up to date as of 11/07/19'